---
#
# Ansible playbook to prepare a Bitrise OS X VM/box, used through vagrant
#

- hosts: all
  # accelerate: true
  remote_user: vagrant
  become_method: sudo
  vars:
    - ansible_sudo_pass: vagrant
    - param_user: vagrant
  roles:
    - ssh-setup
    - profiles
    - intermediate-setup
    - xcode-setup
    - cmd-bridge
    - misc-setup
    - node
    - certs
