---
- name: Apple certificate download
  get_url:
    url: https://www.apple.com/certificateauthority/AppleWWDRCAG3.cer
    dest: $HOME/apple_cert.cer
    checksum: md5:08a45128fa238443623421dd2c9887ab

- name: Add Apple certificate
  shell: bash -l -c "sudo security add-certificates -k /Library/Keychains/System.keychain $HOME/apple_cert.cer"
